# render.yaml

services:
  - type: web
    name: contact-manager-backend
    runtime: node
    plan: free  # Use 'starter' or higher for more features
    region: oregon  # Adjust based on your target region
    branch: main  # The branch you are deploying from
    buildCommand: "pnpm install"  # Install dependencies
    startCommand: "node src/index.js"  # Start your server
    envVars:
      - key: DATABASE_URL
        value: ./db/contacts.db  # Path to your SQLite database
      - key: NODE_ENV
        value: production
    disk:
      name: contacts-data
      mountPath: /db  # Persistent storage for SQLite database
      sizeGB: 1  # Adjust as needed
